USE ola_analytics
GO

INSERT INTO rides
SELECT * FROM rides_staging;
GO

SELECT
COLUMN_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'rides'
ORDER BY ORDINAL_POSITION

ALTER TABLE rides
ALTER COLUMN booking_status VARCHAR(50);
ALTER TABLE rides ALTER COLUMN vehicle_type VARCHAR(50);
ALTER TABLE rides ALTER COLUMN reason_cancel_customer VARCHAR(200);
ALTER TABLE rides ALTER COLUMN reason_cancel_driver VARCHAR(200);
ALTER TABLE rides ALTER COLUMN incomplete_reason VARCHAR(200);
ALTER TABLE rides ALTER COLUMN payment_method VARCHAR(50);


SELECT COUNT(*) FROM rides

DROP TABLE rides_staging